### ISSUE TITLE
Options not available in Admin panel

### ISSUE THREAD

**Issue by ChonoN** [dani-garcia/bitwarden_rs#1142]
### Subject of the issue
Options not available in Admin panel

### Your environment
1.16.3
* Bitwarden_rs version: 

* Install method: Docker-Azure Web App
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 

### Steps to reproduce
By logging in with admin token

### Expected behaviour
I should be able to change configurations in the admin portal

### Actual behaviour
none of the options are available.

### Relevant logs

![Screenshot 2020-09-14 at 10 43 19](https://user-images.githubusercontent.com/49493993/93064189-86b87c80-f677-11ea-9c31-b1c0729cfe13.png)

**Comment by dinger1986** [comment]
If you click on general settings etc it should drop down and let you change settings.

I setup mine with very basic settings and then configure the rest from the web gui fine.

Daniel



Daniel Lamb

Technical Director

[cid:logo_2094e808-adcc-455a-a5fd-54265dc137fa.jpg]<http://www.flonix.co.uk/>

Flonix Limited
Willowview
Redgorton
Perth
PH1 3EL

Phone: 01738 500400

http://www.flonix.co.uk

Company Reg: SC341802

[cid:fb_11c7c55d-b85e-4b3e-b8d8-daabbed1905e.png]<https://www.facebook.com/Flonixltd/>





________________________________

**Comment by BlackDex** [comment]
@ChonoN, that is strange, I'm also missing some other menu items at the top, even though the version seems to indicate the latest version.
What happens if you press F12 to open the developer console (Chrome and Firefox). And see if there are some errors there.

**Comment by ChonoN** [comment]
@dinger1986 I know that's the normal behaviour however it does not work.

@BlackDex only possible error I see is invalid property value.

**Comment by BlackDex** [comment]
Which browser/os version did you use?

**Comment by ChonoN** [comment]
@BlackDex I've used: Chrome, Edge, Safari both on Windows and MacOS

**Comment by ChonoN** [comment]
I get this in the logs: thread 'main' panicked at 'Failed to turn on WAL: DatabaseError(__Unknown, "locking protocol")': src/main.rs:232

**Comment by BlackDex** [comment]
Where is your storage located?
Is this on a cifs/samba mount or nfs??
That could cause some issues.

**Comment by ChonoN** [comment]
It's an azure storage mount

**Comment by BlackDex** [comment]
Ah, that's problematic.
You could try to disable wal via `ENABLE_DB_WAL=false`
But that could cause some issues with locking and file state.

For azure mysql or postgresql database would probably be better.

**Comment by ChonoN** [comment]
@BlackDex unfortunately that did not work but I'm now onto these errors;

Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'vr'.
bootstrap-native-v4.js:39 Uncaught TypeError: Cannot read property 'style' of null
    at bootstrap-native-v4.js:39
    at bootstrap-native-v4.js:9
    at bootstrap-native-v4.js:10
DevTools failed to load SourceMap: Could not load content for https://vault.xxx.app/bwrs_static/bootstrap.css.map: HTTP error: status code 400, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by BlackDex** [comment]
The `map` error is nothing to worry about, we do not have those files in the web-vault, and they do not matter at all.
What is strange are those errors. Also, the -v4.js file has changed in the latest `testing` image. Could you try if that does work?

**Comment by ChonoN** [comment]
@BlackDex on one instance it is now working and shows a different interface on the other it is still broken and the logs from are;
2020_09_28_RD0003FF74C65B_default_docker.log:
2020-09-28T14:36:19.343856508Z /--------------------------------------------------------------------\
2020-09-28T14:36:19.344731312Z |                       Starting Bitwarden_RS                        |
2020-09-28T14:36:19.344745012Z |                      Version 1.16.3-37776241                       |
2020-09-28T14:36:19.350033236Z |--------------------------------------------------------------------|
2020-09-28T14:36:19.352520947Z | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
2020-09-28T14:36:19.352535647Z | official channels to report bugs/features, regardless of client.   |
2020-09-28T14:36:19.352561647Z | Send usage/configuration questions or feature requests to:         |
2020-09-28T14:36:19.352565847Z |   https://bitwardenrs.discourse.group/                             |
2020-09-28T14:36:19.352569947Z | Report suspected bugs/issues in the software itself at:            |
2020-09-28T14:36:19.352573947Z |   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
2020-09-28T14:36:19.352577947Z \--------------------------------------------------------------------/
2020-09-28T14:36:19.352582247Z 
2020-09-28T14:36:19.754904288Z [WARNING] The following environment variables are being overriden by the config file,
2020-09-28T14:36:19.755634891Z [WARNING] please use the admin panel to make changes to them:
2020-09-28T14:36:19.755648491Z [WARNING] HIBP_API_KEY, SIGNUPS_VERIFY, SIGNUPS_DOMAINS_WHITELIST, ADMIN_TOKEN
2020-09-28T14:36:19.755654291Z 
2020-09-28T14:36:35.541571867Z [2020-09-28 14:36:35.530][panic][ERROR] thread 'main' panicked at 'Can't run migrations: QueryError(DatabaseError(__Unknown, "locking protocol"))': src/db/mod.rs:275
2020-09-28T14:36:35.542292570Z    0: bitwarden_rs::init_logging::{{closure}}
2020-09-28T14:36:35.542305970Z    1: std::panicking::rust_panic_with_hook
2020-09-28T14:36:35.543052674Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:530
2020-09-28T14:36:35.543065774Z    2: rust_begin_unwind
2020-09-28T14:36:35.543070574Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:437
2020-09-28T14:36:35.543850877Z    3: core::panicking::panic_fmt
2020-09-28T14:36:35.543863477Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libcore/panicking.rs:85
2020-09-28T14:36:35.544646381Z    4: core::option::expect_none_failed
2020-09-28T14:36:35.544681181Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libcore/option.rs:1269
2020-09-28T14:36:35.544716581Z    5: bitwarden_rs::db::sqlite_migrations::run_migrations
2020-09-28T14:36:35.544724881Z    6: bitwarden_rs::db::DbPool::from_config
2020-09-28T14:36:35.551075110Z    7: bitwarden_rs::main
2020-09-28T14:36:35.551089810Z    8: std::rt::lang_start::{{closure}}
2020-09-28T14:36:35.551386012Z    9: std::rt::lang_start_internal::{{closure}}
2020-09-28T14:36:35.551408612Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/rt.rs:52
2020-09-28T14:36:35.551733313Z       std::panicking::try::do_call
2020-09-28T14:36:35.551745413Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:348
2020-09-28T14:36:35.551750013Z       std::panicking::try
2020-09-28T14:36:35.552045215Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:325
2020-09-28T14:36:35.552056415Z       std::panic::catch_unwind
2020-09-28T14:36:35.552060715Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panic.rs:394
2020-09-28T14:36:35.552343916Z       std::rt::lang_start_internal
2020-09-28T14:36:35.552363916Z              at rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/rt.rs:51
2020-09-28T14:36:35.552367816Z   10: main
2020-09-28T14:36:35.552371216Z   11: __libc_start_main
2020-09-28T14:36:35.552374816Z   12: _start
2020-09-28T14:36:35.552908219Z 

2020_09_28_RD0003FF74C65B_docker.log:
2020-09-28T14:35:15.613Z INFO  - Recycling container because of AppFrameworkVersionChange and appFrameworkVersion = bitwardenrs/server:testing
2020-09-28T14:35:15.851Z INFO  - Pulling image from Docker hub: bitwardenrs/server:testing
2020-09-28T14:35:17.141Z INFO  - testing Pulling from bitwardenrs/server
2020-09-28T14:35:18.085Z INFO  - d121f8d1c412 Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - add804d45af6 Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - 11c2acf2c6dc Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - 7039fd29a26c Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - a07af498d11c Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - 9d54247e7b45 Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - b5d29d3ace9a Pulling fs layer
2020-09-28T14:35:18.085Z INFO  - 065785c049b0 Pulling fs layer
2020-09-28T14:35:19.362Z INFO  - b5d29d3ace9a Downloading 877B / 877B
2020-09-28T14:35:19.362Z INFO  - b5d29d3ace9a Verifying Checksum
2020-09-28T14:35:19.363Z INFO  - b5d29d3ace9a Download complete
2020-09-28T14:35:19.801Z INFO  - 065785c049b0 Downloading 218B / 218B
2020-09-28T14:35:19.802Z INFO  - 065785c049b0 Verifying Checksum
2020-09-28T14:35:19.802Z INFO  - 065785c049b0 Download complete
2020-09-28T14:35:20.191Z INFO  - 7039fd29a26c Downloading 145B / 145B
2020-09-28T14:35:20.191Z INFO  - 7039fd29a26c Verifying Checksum
2020-09-28T14:35:20.191Z INFO  - 7039fd29a26c Download complete
2020-09-28T14:35:20.739Z INFO  - add804d45af6 Downloading 1MB / 16MB
2020-09-28T14:35:20.952Z INFO  - d121f8d1c412 Downloading 1MB / 25MB
2020-09-28T14:35:21.051Z INFO  - add804d45af6 Downloading 2MB / 16MB
2020-09-28T14:35:21.114Z INFO  - add804d45af6 Downloading 3MB / 16MB
2020-09-28T14:35:21.115Z INFO  - d121f8d1c412 Downloading 2MB / 25MB
2020-09-28T14:35:21.331Z INFO  - add804d45af6 Downloading 6MB / 16MB
2020-09-28T14:35:21.408Z INFO  - add804d45af6 Downloading 7MB / 16MB
2020-09-28T14:35:21.525Z INFO  - add804d45af6 Downloading 8MB / 16MB
2020-09-28T14:35:21.795Z INFO  - add804d45af6 Downloading 9MB / 16MB
2020-09-28T14:35:21.989Z INFO  - 9d54247e7b45 Downloading 2MB / 8MB
2020-09-28T14:35:21.990Z INFO  - d121f8d1c412 Downloading 7MB / 25MB
2020-09-28T14:35:22.142Z INFO  - 9d54247e7b45 Downloading 3MB / 8MB
2020-09-28T14:35:22.420Z INFO  - d121f8d1c412 Downloading 10MB / 25MB
2020-09-28T14:35:22.507Z INFO  - 9d54247e7b45 Downloading 5MB / 8MB
2020-09-28T14:35:22.524Z INFO  - 9d54247e7b45 Downloading 6MB / 8MB
2020-09-28T14:35:22.545Z INFO  - d121f8d1c412 Downloading 11MB / 25MB
2020-09-28T14:35:22.640Z INFO  - add804d45af6 Verifying Checksum
2020-09-28T14:35:22.641Z INFO  - add804d45af6 Download complete
2020-09-28T14:35:22.649Z INFO  - 9d54247e7b45 Downloading 8MB / 8MB
2020-09-28T14:35:22.659Z INFO  - d121f8d1c412 Downloading 14MB / 25MB
2020-09-28T14:35:22.660Z INFO  - 11c2acf2c6dc Downloading 93B / 93B
2020-09-28T14:35:22.661Z INFO  - 11c2acf2c6dc Verifying Checksum
2020-09-28T14:35:22.661Z INFO  - 11c2acf2c6dc Download complete
2020-09-28T14:35:22.668Z INFO  - 9d54247e7b45 Verifying Checksum
2020-09-28T14:35:22.668Z INFO  - 9d54247e7b45 Download complete
2020-09-28T14:35:22.760Z INFO  - d121f8d1c412 Downloading 18MB / 25MB
2020-09-28T14:35:22.941Z INFO  - d121f8d1c412 Downloading 21MB / 25MB
2020-09-28T14:35:23.036Z INFO  - d121f8d1c412 Downloading 24MB / 25MB
2020-09-28T14:35:23.055Z INFO  - d121f8d1c412 Verifying Checksum
2020-09-28T14:35:23.055Z INFO  - d121f8d1c412 Download complete
2020-09-28T14:35:25.297Z INFO  - d121f8d1c412 Extracting 3MB / 25MB
2020-09-28T14:35:25.806Z INFO  - d121f8d1c412 Extracting 4MB / 25MB
2020-09-28T14:35:25.976Z INFO  - a07af498d11c Downloading 451KB / 6MB
2020-09-28T14:35:26.177Z INFO  - a07af498d11c Downloading 1MB / 6MB
2020-09-28T14:35:26.411Z INFO  - a07af498d11c Downloading 5MB / 6MB
2020-09-28T14:35:26.451Z INFO  - a07af498d11c Verifying Checksum
2020-09-28T14:35:26.452Z INFO  - a07af498d11c Download complete
2020-09-28T14:35:26.766Z INFO  - d121f8d1c412 Extracting 4MB / 25MB
2020-09-28T14:35:26.944Z INFO  - d121f8d1c412 Extracting 5MB / 25MB
2020-09-28T14:35:27.100Z INFO  - d121f8d1c412 Extracting 5MB / 25MB
2020-09-28T14:35:28.421Z INFO  - d121f8d1c412 Extracting 7MB / 25MB
2020-09-28T14:35:28.538Z INFO  - d121f8d1c412 Extracting 7MB / 25MB
2020-09-28T14:35:28.647Z INFO  - d121f8d1c412 Extracting 8MB / 25MB
2020-09-28T14:35:28.784Z INFO  - d121f8d1c412 Extracting 9MB / 25MB
2020-09-28T14:35:29.308Z INFO  - d121f8d1c412 Extracting 11MB / 25MB
2020-09-28T14:35:29.678Z INFO  - d121f8d1c412 Extracting 12MB / 25MB
2020-09-28T14:35:29.875Z INFO  - d121f8d1c412 Extracting 13MB / 25MB
2020-09-28T14:35:30.106Z INFO  - d121f8d1c412 Extracting 14MB / 25MB
2020-09-28T14:35:30.256Z INFO  - d121f8d1c412 Extracting 14MB / 25MB
2020-09-28T14:35:30.428Z INFO  - d121f8d1c412 Extracting 15MB / 25MB
2020-09-28T14:35:30.740Z INFO  - d121f8d1c412 Extracting 15MB / 25MB
2020-09-28T14:35:30.948Z INFO  - d121f8d1c412 Extracting 16MB / 25MB
2020-09-28T14:35:31.184Z INFO  - d121f8d1c412 Extracting 16MB / 25MB
2020-09-28T14:35:31.369Z INFO  - d121f8d1c412 Extracting 17MB / 25MB
2020-09-28T14:35:32.008Z INFO  - d121f8d1c412 Extracting 20MB / 25MB
2020-09-28T14:35:33.270Z INFO  - d121f8d1c412 Extracting 23MB / 25MB
2020-09-28T14:35:33.789Z INFO  - d121f8d1c412 Extracting 24MB / 25MB
2020-09-28T14:35:35.342Z INFO  - d121f8d1c412 Extracting 25MB / 25MB
2020-09-28T14:35:36.331Z INFO  - d121f8d1c412 Extracting 25MB / 25MB
2020-09-28T14:35:37.327Z INFO  - d121f8d1c412 Pull complete
2020-09-28T14:35:39.052Z INFO  - add804d45af6 Extracting 384KB / 16MB
2020-09-28T14:35:39.167Z INFO  - add804d45af6 Extracting 768KB / 16MB
2020-09-28T14:35:39.300Z INFO  - add804d45af6 Extracting 1MB / 16MB
2020-09-28T14:35:39.952Z INFO  - add804d45af6 Extracting 2MB / 16MB
2020-09-28T14:35:40.461Z INFO  - add804d45af6 Extracting 2MB / 16MB
2020-09-28T14:35:41.602Z INFO  - add804d45af6 Extracting 3MB / 16MB
2020-09-28T14:35:42.731Z INFO  - add804d45af6 Extracting 3MB / 16MB
2020-09-28T14:35:43.075Z INFO  - add804d45af6 Extracting 4MB / 16MB
2020-09-28T14:35:43.648Z INFO  - add804d45af6 Extracting 4MB / 16MB
2020-09-28T14:35:44.041Z INFO  - add804d45af6 Extracting 4MB / 16MB
2020-09-28T14:35:44.739Z INFO  - add804d45af6 Extracting 5MB / 16MB
2020-09-28T14:35:44.859Z INFO  - add804d45af6 Extracting 6MB / 16MB
2020-09-28T14:35:45.217Z INFO  - add804d45af6 Extracting 7MB / 16MB
2020-09-28T14:35:45.800Z INFO  - add804d45af6 Extracting 9MB / 16MB
2020-09-28T14:35:46.249Z INFO  - add804d45af6 Extracting 10MB / 16MB
2020-09-28T14:35:46.592Z INFO  - add804d45af6 Extracting 12MB / 16MB
2020-09-28T14:35:46.877Z INFO  - add804d45af6 Extracting 12MB / 16MB
2020-09-28T14:35:47.676Z INFO  - add804d45af6 Extracting 15MB / 16MB
2020-09-28T14:35:47.789Z INFO  - add804d45af6 Extracting 15MB / 16MB
2020-09-28T14:35:49.274Z INFO  - add804d45af6 Extracting 15MB / 16MB
2020-09-28T14:35:49.927Z INFO  - add804d45af6 Extracting 16MB / 16MB
2020-09-28T14:35:52.503Z INFO  - add804d45af6 Pull complete
2020-09-28T14:35:53.473Z INFO  - 11c2acf2c6dc Extracting 93B / 93B
2020-09-28T14:35:53.485Z INFO  - 11c2acf2c6dc Extracting 93B / 93B
2020-09-28T14:35:54.873Z INFO  - 11c2acf2c6dc Pull complete
2020-09-28T14:35:55.256Z INFO  - 7039fd29a26c Extracting 145B / 145B
2020-09-28T14:35:55.258Z INFO  - 7039fd29a26c Extracting 145B / 145B
2020-09-28T14:35:56.985Z INFO  - 7039fd29a26c Pull complete
2020-09-28T14:35:57.654Z INFO  - a07af498d11c Extracting 192KB / 6MB
2020-09-28T14:35:57.765Z INFO  - a07af498d11c Extracting 576KB / 6MB
2020-09-28T14:35:58.078Z INFO  - a07af498d11c Extracting 1MB / 6MB
2020-09-28T14:35:58.296Z INFO  - a07af498d11c Extracting 2MB / 6MB
2020-09-28T14:35:58.648Z INFO  - a07af498d11c Extracting 3MB / 6MB
2020-09-28T14:35:59.090Z INFO  - a07af498d11c Extracting 5MB / 6MB
2020-09-28T14:35:59.437Z INFO  - a07af498d11c Extracting 6MB / 6MB
2020-09-28T14:35:59.455Z INFO  - a07af498d11c Extracting 6MB / 6MB
2020-09-28T14:36:00.345Z INFO  - a07af498d11c Pull complete
2020-09-28T14:36:01.370Z INFO  - 9d54247e7b45 Extracting 192KB / 8MB
2020-09-28T14:36:01.486Z INFO  - 9d54247e7b45 Extracting 384KB / 8MB
2020-09-28T14:36:02.153Z INFO  - 9d54247e7b45 Extracting 1MB / 8MB
2020-09-28T14:36:02.269Z INFO  - 9d54247e7b45 Extracting 2MB / 8MB
2020-09-28T14:36:02.713Z INFO  - 9d54247e7b45 Extracting 4MB / 8MB
2020-09-28T14:36:02.815Z INFO  - 9d54247e7b45 Extracting 5MB / 8MB
2020-09-28T14:36:02.943Z INFO  - 9d54247e7b45 Extracting 6MB / 8MB
2020-09-28T14:36:03.040Z INFO  - 9d54247e7b45 Extracting 6MB / 8MB
2020-09-28T14:36:03.162Z INFO  - 9d54247e7b45 Extracting 6MB / 8MB
2020-09-28T14:36:03.278Z INFO  - 9d54247e7b45 Extracting 7MB / 8MB
2020-09-28T14:36:03.542Z INFO  - 9d54247e7b45 Extracting 8MB / 8MB
2020-09-28T14:36:03.570Z INFO  - 9d54247e7b45 Extracting 8MB / 8MB
2020-09-28T14:36:04.500Z INFO  - 9d54247e7b45 Pull complete
2020-09-28T14:36:04.939Z INFO  - b5d29d3ace9a Extracting 877B / 877B
2020-09-28T14:36:04.949Z INFO  - b5d29d3ace9a Extracting 877B / 877B
2020-09-28T14:36:06.182Z INFO  - b5d29d3ace9a Pull complete
2020-09-28T14:36:06.500Z INFO  - 065785c049b0 Extracting 218B / 218B
2020-09-28T14:36:06.508Z INFO  - 065785c049b0 Extracting 218B / 218B
2020-09-28T14:36:08.124Z INFO  - 065785c049b0 Pull complete
2020-09-28T14:36:11.265Z INFO  -  Digest: sha256:xxxa73cxxx
2020-09-28T14:36:11.841Z INFO  -  Status: Downloaded newer image for bitwardenrs/server:testing
2020-09-28T14:36:11.860Z INFO  - Pull Image successful, Time taken: 0 Minutes and 56 Seconds
2020-09-28T14:36:12.010Z INFO  - Starting container for site
2020-09-28T14:36:12.010Z INFO  - PID 

2020-09-28T14:36:12.010Z INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2020-09-28T14:36:18.466Z INFO  - Initiating warmup request to container xxx for site pxxx
2020-09-28T14:36:33.687Z INFO  - Waiting for response to warmup request for container xxx. Elapsed time = 15.2209503 sec
2020-09-28T14:36:38.005Z ERROR - Container xxx for site pxxx has exited, failing site start
2020-09-28T14:36:38.020Z ERROR - Container xxx didn't respond to HTTP pings on port: 80, failing site start. See container logs for debugging.
2020-09-28T14:39:33.706Z INFO  - Pulling image from Docker hub: bitwardenrs/server:testing
2020-09-28T14:39:35.093Z INFO  - testing Pulling from bitwardenrs/server
2020-09-28T14:39:35.469Z INFO  -  Digest: sha256:xxxa73cxxx
2020-09-28T14:39:35.471Z INFO  -  Status: Image is up to date for bitwardenrs/server:testing
2020-09-28T14:39:35.485Z INFO  - Pull Image successful, Time taken: 0 Minutes and 1 Seconds
2020-09-28T14:39:35.511Z INFO  - Starting container for site
2020-09-28T14:39:35.512Z INFO  - docker run -d -p 5698:80 --name pxxx_0_b2fba7cc -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=true -e WEBSITE_SITE_NAME=pxxx -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=pxxx.azurewebsites.net -e WEBSITE_INSTANCE_ID=4xxxx bitwardenrs/server:testing  

2020-09-28T14:39:35.513Z INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2020-09-28T14:39:40.339Z INFO  - Initiating warmup request to container xxx for site xxx
2020-09-28T14:39:45.335Z INFO  - Container pxxx_0_b2fba7cc for site pxxx initialized successfully and is ready to serve requests.
2020-09-28T15:12:22.234Z INFO  - Recycling container because of AppFrameworkVersionChange and appFrameworkVersion = bitwardenrs/server:latest
2020-09-28T15:12:22.378Z INFO  - Pulling image from Docker hub: bitwardenrs/server:latest
2020-09-28T15:12:24.072Z INFO  - latest Pulling from bitwardenrs/server
2020-09-28T15:12:24.525Z INFO  - bf5952930446 Already exists
2020-09-28T15:12:24.814Z INFO  - 709602047d73 Pulling fs layer
2020-09-28T15:12:24.815Z INFO  - c875b592fe57 Pulling fs layer
2020-09-28T15:12:24.815Z INFO  - 56f2e2e26aa0 Pulling fs layer
2020-09-28T15:12:24.816Z INFO  - 245ef0ff254a Pulling fs layer
2020-09-28T15:12:24.817Z INFO  - 6bce9435c980 Pulling fs layer
2020-09-28T15:12:24.818Z INFO  - 5b32adb29106 Pulling fs layer
2020-09-28T15:12:24.818Z INFO  - de9e744c897d Pulling fs layer
2020-09-28T15:12:25.882Z INFO  - c875b592fe57 Downloading 93B / 93B
2020-09-28T15:12:25.884Z INFO  - c875b592fe57 Verifying Checksum
2020-09-28T15:12:25.884Z INFO  - c875b592fe57 Download complete
2020-09-28T15:12:26.013Z INFO  - 5b32adb29106 Downloading 424B / 876B
2020-09-28T15:12:26.013Z INFO  - 5b32adb29106 Downloading 876B / 876B
2020-09-28T15:12:26.014Z INFO  - 5b32adb29106 Verifying Checksum
2020-09-28T15:12:26.015Z INFO  - 5b32adb29106 Download complete
2020-09-28T15:12:26.498Z INFO  - 245ef0ff254a Verifying Checksum
2020-09-28T15:12:26.504Z INFO  - 245ef0ff254a Download complete
2020-09-28T15:12:26.955Z INFO  - de9e744c897d Downloading 217B / 217B
2020-09-28T15:12:26.958Z INFO  - de9e744c897d Verifying Checksum
2020-09-28T15:12:26.959Z INFO  - de9e744c897d Download complete
2020-09-28T15:12:28.743Z INFO  - 56f2e2e26aa0 Downloading 147B / 147B
2020-09-28T15:12:28.744Z INFO  - 56f2e2e26aa0 Verifying Checksum
2020-09-28T15:12:28.745Z INFO  - 56f2e2e26aa0 Download complete
2020-09-28T15:12:29.108Z INFO  - 709602047d73 Downloading 5MB / 6MB
2020-09-28T15:12:29.109Z INFO  - 709602047d73 Verifying Checksum
2020-09-28T15:12:29.110Z INFO  - 709602047d73 Download complete
2020-09-28T15:12:29.657Z INFO  - 6bce9435c980 Downloading 6MB / 7MB
2020-09-28T15:12:29.704Z INFO  - 6bce9435c980 Verifying Checksum
2020-09-28T15:12:29.705Z INFO  - 6bce9435c980 Download complete
2020-09-28T15:12:29.733Z INFO  - 709602047d73 Extracting 192KB / 6MB
2020-09-28T15:12:30.703Z INFO  - 709602047d73 Extracting 3MB / 6MB
2020-09-28T15:12:30.812Z INFO  - 709602047d73 Extracting 3MB / 6MB
2020-09-28T15:12:31.487Z INFO  - 709602047d73 Extracting 5MB / 6MB
2020-09-28T15:12:32.275Z INFO  - 709602047d73 Extracting 6MB / 6MB
2020-09-28T15:12:33.605Z INFO  - 709602047d73 Pull complete
2020-09-28T15:12:34.607Z INFO  - c875b592fe57 Extracting 93B / 93B
2020-09-28T15:12:34.608Z INFO  - c875b592fe57 Extracting 93B / 93B
2020-09-28T15:12:38.621Z INFO  - c875b592fe57 Pull complete
2020-09-28T15:12:38.622Z INFO  - 56f2e2e26aa0 Extracting 147B / 147B
2020-09-28T15:12:38.623Z INFO  - 56f2e2e26aa0 Extracting 147B / 147B
2020-09-28T15:12:38.624Z INFO  - 56f2e2e26aa0 Pull complete
2020-09-28T15:12:38.630Z INFO  - 245ef0ff254a Extracting 192KB / 6MB
2020-09-28T15:12:38.631Z INFO  - 245ef0ff254a Extracting 576KB / 6MB
2020-09-28T15:12:38.631Z INFO  - 245ef0ff254a Extracting 960KB / 6MB
2020-09-28T15:12:38.632Z INFO  - 245ef0ff254a Extracting 1MB / 6MB
2020-09-28T15:12:38.633Z INFO  - 245ef0ff254a Extracting 1MB / 6MB
2020-09-28T15:12:40.627Z INFO  - 245ef0ff254a Extracting 3MB / 6MB
2020-09-28T15:12:40.628Z INFO  - 245ef0ff254a Extracting 3MB / 6MB
2020-09-28T15:12:40.629Z INFO  - 245ef0ff254a Extracting 4MB / 6MB
2020-09-28T15:12:40.635Z INFO  - 245ef0ff254a Extracting 6MB / 6MB
2020-09-28T15:12:40.637Z INFO  - 245ef0ff254a Extracting 6MB / 6MB
2020-09-28T15:12:40.955Z INFO  - 245ef0ff254a Pull complete


Also attached are two images showing the portal. The one with 1.16.3 is the broken one.
![Screenshot 2020-09-28 at 17 23 45](https://user-images.githubusercontent.com/49493993/94452159-86f46400-01af-11eb-98f0-845860379ba8.png)
![Screenshot 2020-09-28 at 17 22 52](https://user-images.githubusercontent.com/49493993/94452167-88be2780-01af-11eb-8a9b-3e5f1cae0976.png)

**Comment by BlackDex** [comment]
The version shouldn't be at the top right anymore at all.
Do you maybe have the admin templates overruled somewhere??
Also check the config option `RELOAD_TEMPLATES` is set to false and you have the `TEMPLATE_FOLDER` not set at all.
Also check the config.json in the data folder.

**Comment by ChonoN** [comment]
@BlackDex Thanks for the help a combination of all the above solved it but I now have a fresh new issue in that I don't see any data or organisations when I roll back to latest from testing.

**Comment by BlackDex** [comment]
You rolled-back from the docker hub `testing` to `latest` tag?
If you did that you would have an image from the 9th of August, which is a bit older, but should work.
Also, there shouldn't be any big differences between the `testing` (master branch) and the `latest` (tagged) versions which could cause that.

If you login into the admin panel, do you also not see any users or orgs there?

**Comment by BlackDex** [comment]
Also, i don't know how Azure rolls out these docker images. But i have seen people who are using composer with the same issues.
They actually had to stop the container, change the docker tag to either latest, testing or 1.17.0, do a new pull, and start it again for it to work. Probably some caching stuff. Maybe that is the case also.

But please check the admin panel if you can see the users/orgs there including the statistics.

**Comment by ChonoN** [comment]
Hi @BlackDex I did the above prior and it worked, thanks for the help in resolving the issue.
