### ISSUE TITLE
Icon download crashed bitwarden_rs process

### ISSUE THREAD

**Issue by avoidik** [dani-garcia/bitwarden_rs#1352]
### Subject of the issue
I've imported my database from keepass2 xml into bitwarden_rs using web-vault interface. After doing that I noticed that bitwarden_rs daemon started to fail very often.

### Your environment

* Bitwarden_rs version: 1.18.0

* Install method: Built from the source
* Clients used: Web-Vault v2.18.1
* Reverse proxy and version: None
* Version of mysql/postgresql: sqlite
* Other relevant information:

### Steps to reproduce

You can reproduce failure behavior by sending multiple requests like:

```bash
for i in $(seq 1 5); do curl -sv https://192.168.88.220:8000/icons/blah/icon.png; sleep 3; done
```

### Expected behaviour

Gently handle the failure

### Actual behaviour

Panic, termination

### Relevant logs

<details>
  <summary>Click to expand (152 lines)</summary>
  
```
-- Logs begin at Thu 2020-12-24 15:55:10 EET. --
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: | Send usage/configuration questions or feature requests to:         |
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: |   https://bitwardenrs.discourse.group/                             |
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: | Report suspected bugs/issues in the software itself at:            |
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: |   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: \--------------------------------------------------------------------/
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: [WARNING] The following environment variables are being overriden by the config file,
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: [WARNING] please use the admin panel to make changes to them:
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: [WARNING] DOMAIN, DISABLE_ICON_DOWNLOAD, ORG_CREATION_USERS, INVITATIONS_ALLOWED, SHOW_PASSWORD_HINT, ADMIN_TOKEN, IP_HEADER, ICON_CACHE_TTL, DISABLE_ADMIN_TOKEN
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:12:56.651][parity_ws][INFO] Listening for new connections on 192.168.88.220:3012.
Feb 03 17:12:56 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:12:56.657][start][INFO] Rocket has launched from https://0.0.0.0:8000
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:15:44.555][request][INFO] GET /icons/blah/icon.png
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:15:44.637][panic][ERROR] thread 'reqwest-internal-sync-runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }': /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.24/src/runtime/blocking/pool.rs:234
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    0: backtrace::backtrace::trace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    1: backtrace::capture::Backtrace::new
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    2: bitwarden_rs::init_logging::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    3: std::panicking::rust_panic_with_hook
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:595:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    4: std::panicking::begin_panic_handler::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:497:13
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    5: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys_common/backtrace.rs:141:18
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    6: rust_begin_unwind
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:493:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    7: core::panicking::panic_fmt
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/panicking.rs:92:14
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    8: core::option::expect_none_failed
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/option.rs:1268:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    9: tokio::runtime::blocking::pool::Spawner::spawn
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   10: tokio::runtime::blocking::pool::spawn_blocking
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   11: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   16: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   18: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   19: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   20: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   22: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   23: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   25: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   27: <hyper::client::ResponseFuture as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   28: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   31: tokio::runtime::task::harness::Harness<T,S>::poll
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   32: std::thread::local::LocalKey<T>::with
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   33: tokio::macros::scoped_tls::ScopedKey<T>::set
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   34: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   35: tokio::runtime::context::enter
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   36: tokio::runtime::handle::Handle::enter
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   37: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   38: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::sys::unix::thread::Thread::new::thread_start
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys/unix/thread.rs:71:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:15:44.644][panic][ERROR] thread 'unnamed' panicked at 'event loop thread panicked': /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/reqwest-0.10.10/src/blocking/client.rs:921
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    0: backtrace::backtrace::trace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    1: backtrace::capture::Backtrace::new
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    2: bitwarden_rs::init_logging::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    3: std::panicking::rust_panic_with_hook
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:595:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    4: std::panicking::begin_panic::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    5: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    6: std::panicking::begin_panic
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    7: reqwest::blocking::client::event_loop_panicked
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    8: reqwest::blocking::client::ClientHandle::execute_request::{{closure}}::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    9: reqwest::blocking::wait::timeout
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   10: reqwest::blocking::client::Client::execute
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   11: reqwest::blocking::request::RequestBuilder::send
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   12: bitwarden_rs::api::icons::get_page_with_cookies
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   13: bitwarden_rs::api::icons::download_icon
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   14: bitwarden_rs::api::icons::rocket_route_fn_icon
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   15: <F as rocket::handler::Handler>::handle
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   16: rocket::rocket::Rocket::route_and_process
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   17: <rocket::rocket::Rocket as hyper::server::Handler>::handle
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   18: hyper::server::Worker<H>::handle_connection
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   19: hyper::server::listener::spawn_with::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   20: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::sys::unix::thread::Thread::new::thread_start
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys/unix/thread.rs:71:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:15:44.645][panic][ERROR] thread 'unnamed' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }': /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/thread/mod.rs:620
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    0: backtrace::backtrace::trace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    1: backtrace::capture::Backtrace::new
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    2: bitwarden_rs::init_logging::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    3: std::panicking::rust_panic_with_hook
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:595:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    4: std::panicking::begin_panic_handler::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:497:13
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    5: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys_common/backtrace.rs:141:18
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    6: rust_begin_unwind
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:493:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    7: core::panicking::panic_fmt
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/panicking.rs:92:14
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    8: core::option::expect_none_failed
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/option.rs:1268:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    9: hyper::server::listener::spawn_with
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   10: hyper::server::listener::ListenerPool<A>::accept
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   11: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/alloc/src/boxed.rs:1318:9
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::sys::unix::thread::Thread::new::thread_start
Feb 03 17:15:44 raspberrypi systemd[1]: bitwarden_rs.service: Main process exited, code=exited, status=101/n/a
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys/unix/thread.rs:71:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]: [2021-02-03 17:15:44.646][panic][ERROR] thread 'main' panicked at 'internal error: entered unreachable code: the call to `handle_threads` should block on success': /home/pi/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/263e39b/core/lib/src/rocket.rs:751
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    0: backtrace::backtrace::trace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    1: backtrace::capture::Backtrace::new
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    2: bitwarden_rs::init_logging::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    3: std::panicking::rust_panic_with_hook
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:595:17
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    4: std::panicking::begin_panic_handler::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:497:13
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    5: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys_common/backtrace.rs:141:18
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    6: rust_begin_unwind
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:493:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    7: std::panicking::begin_panic_fmt
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:435:5
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    8: rocket::rocket::Rocket::launch
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:    9: bitwarden_rs::main
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   10: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   11: std::rt::lang_start::{{closure}}
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/ops/function.rs:259:13
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::panicking::try::do_call
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:379:40
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::panicking::try
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:343:19
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::panic::catch_unwind
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panic.rs:396:14
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:       std::rt::lang_start_internal
Feb 03 17:15:44 raspberrypi systemd[1]: bitwarden_rs.service: Failed with result 'exit-code'.
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:              at /rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/rt.rs:51:25
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   13: main
Feb 03 17:15:44 raspberrypi bitwarden_rs[12567]:   14: __libc_start_main
```
</details>

**Comment by avoidik** [comment]
## Workaround

```
DISABLE_ICON_DOWNLOAD=true
```

**Comment by avoidik** [comment]
Duplicate https://github.com/dani-garcia/bitwarden_rs/issues/1202
