### ISSUE TITLE
iOS client cannot connect

### ISSUE THREAD

**Issue by RitzyMage** [dani-garcia/bitwarden_rs#1564]
### Subject of the issue
When connecting with the Bitwarden iOS app, it fails with only the message: "An error has occurred". Looking in the server logs shows:

```
[2021-03-30 13:26:43.060][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
Mar 30 13:26:43 main-server bitwarden_rs[2432]: [2021-03-30 13:26:43.196][request][INFO] POST /identity/connect/token
Mar 30 13:26:43 main-server bitwarden_rs[2432]: [2021-03-30 13:26:43.350][panic][ERROR] thread 'unnamed' panicked at 'Lazy instance has previously been poisoned': (my home directory)/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.7.2/src/lib.rs:1024
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    0: bitwarden_rs::init_logging::{{closure}}
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    1: std::panicking::rust_panic_with_hook
Mar 30 13:26:43 main-server bitwarden_rs[2432]:              at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/std/src/panicking.rs:595:17
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    2: std::panicking::begin_panic::{{closure}}
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    4: std::panicking::begin_panic
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    5: once_cell::imp::OnceCell<T>::initialize::{{closure}}
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    6: once_cell::imp::initialize_inner
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    7: once_cell::imp::OnceCell<T>::initialize
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    8: bitwarden_rs::auth::encode_jwt
Mar 30 13:26:43 main-server bitwarden_rs[2432]:    9: bitwarden_rs::db::models::device::Device::refresh_tokens
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   10: bitwarden_rs::api::identity::_password_login
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   11: bitwarden_rs::api::identity::rocket_route_fn_login
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   12: <F as rocket::handler::Handler>::handle
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   13: rocket::rocket::Rocket::route_and_process
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   14: <rocket::rocket::Rocket as hyper::server::Handler>::handle
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   15: hyper::server::Worker<H>::handle_connection
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   16: hyper::server::listener::spawn_with::{{closure}}
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   17: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   18: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 30 13:26:43 main-server bitwarden_rs[2432]:              at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/alloc/src/boxed.rs:1546:9
Mar 30 13:26:43 main-server bitwarden_rs[2432]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 30 13:26:43 main-server bitwarden_rs[2432]:              at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/alloc/src/boxed.rs:1546:9
Mar 30 13:26:43 main-server bitwarden_rs[2432]:       std::sys::unix::thread::Thread::new::thread_start
Mar 30 13:26:43 main-server bitwarden_rs[2432]:              at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/std/src/sys/unix/thread.rs:71:17
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   20: start_thread
Mar 30 13:26:43 main-server bitwarden_rs[2432]:   21: clone
```

This only happens if I type in the CORRECT master password, so it is definitely coming from the server. In addition, the chrome extension client and web vault both work great (including the SSL certificates).

### Deployment environment

* bitwarden_rs version: 1.20.0-9b2234fa

* Install method: built from source

* Clients used: iOS app

* Reverse proxy and version: nginx/1.18.0

* MySQL/MariaDB or PostgreSQL version: mysql  Ver 15.1 Distrib 10.3.25-MariaDB

### Steps to reproduce

I started bitwarden_rs using the instructions at [https://github.com/dani-garcia/bitwarden_rs/wiki/Setup-as-a-systemd-service](https://github.com/dani-garcia/bitwarden_rs/wiki/Setup-as-a-systemd-service)

### Expected behaviour

I expect the iOS client to log me in on a valid master password and let me access my vault.

### Actual behaviour

Got the vague error message "An error occurred" and was not logged in.

**Comment by RitzyMage** [comment]
UPDATE: I really wanted to get this working, so I figured out how to "fix" this problem: setting my server version to 1.20.0 rather than just master. This bug must have been introduced after.

In addition, I  found that this wasn't exclusive to the iOS client; it also happened on other computers. It seemed to only work on the first computer I logged in on.

**Comment by BlackDex** [comment]
Do you have the LimitNPROC setting configured?
If so, either remove or increase that value.
