### ISSUE TITLE
Duo Login - An unexpected error has occured 

### ISSUE THREAD

**Issue by TuEstUnePommeDeTerre** [dani-garcia/bitwarden_rs#579]
I am unable to log in to the web and desktop clients with Duo enabled.
![Screenshot from 2019-08-17 17-36-13](https://user-images.githubusercontent.com/5674386/63218022-b6185500-c116-11e9-91f8-fb418176db2a.png)

However, it does work on the Android app and the web vault.

I've included my docker log with RUST_BACKTRACE=full

```bitwarden_1  | [2019-08-17 17:36:30][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Outcome: Success
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Response succeeded.
bitwarden_1  | [2019-08-17 17:36:30][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Matched: POST /identity/connect/token (login)
bitwarden_1  | [2019-08-17 17:36:30][bitwarden_rs::error][ERROR] JsonError. {"TwoFactorProviders":[2],"TwoFactorProviders2":{"2":{"Host":"api-80fdd41a.duosecurity.com","Signature":"**REDACTED**"}},"error":"invalid_grant","error_description":"Two factor required."}
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Outcome: Success
bitwarden_1  | [2019-08-17 17:36:30][_][INFO] Response succeeded.
bitwarden_1  | [2019-08-17 17:36:39][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
bitwarden_1  | [2019-08-17 17:36:39][_][INFO] Matched: POST /identity/connect/token (login)
bitwarden_1  | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" })', src/libcore/result.rs:1051:5
bitwarden_1  | stack backtrace:
bitwarden_1  |    0:     0x55f4e2f4721b - backtrace::backtrace::libunwind::trace::h4f04af92f39f2b78
bitwarden_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
bitwarden_1  |    1:     0x55f4e2f4721b - backtrace::backtrace::trace_unsynchronized::hb28ce8d2b7fb3e31
bitwarden_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
bitwarden_1  |    2:     0x55f4e2f4721b - std::sys_common::backtrace::_print::he3f49d2d13a51ff1
bitwarden_1  |                                at src/libstd/sys_common/backtrace.rs:47
bitwarden_1  |    3:     0x55f4e2f4721b - std::sys_common::backtrace::print::h46c2f3b13519e9bf
bitwarden_1  |                                at src/libstd/sys_common/backtrace.rs:36
bitwarden_1  |    4:     0x55f4e2f4721b - std::panicking::default_hook::{{closure}}::h6694acddafc67583
bitwarden_1  |                                at src/libstd/panicking.rs:200
bitwarden_1  |    5:     0x55f4e2f46ef7 - std::panicking::default_hook::hb4761d2feeb6d93c
bitwarden_1  |                                at src/libstd/panicking.rs:214
bitwarden_1  |    6:     0x55f4e2f47990 - std::panicking::rust_panic_with_hook::h7a5f9620b0a832bc
bitwarden_1  |                                at src/libstd/panicking.rs:477
bitwarden_1  |    7:     0x55f4e2f47512 - std::panicking::continue_panic_fmt::h76588b16c9674f9c
bitwarden_1  |                                at src/libstd/panicking.rs:384
bitwarden_1  |    8:     0x55f4e2f473f6 - rust_begin_unwind
bitwarden_1  |                                at src/libstd/panicking.rs:311
bitwarden_1  |    9:     0x55f4e2f6994d - core::panicking::panic_fmt::hcce9be08ab68e123
bitwarden_1  |                                at src/libcore/panicking.rs:85
bitwarden_1  |   10:     0x55f4e266f63e - core::result::unwrap_failed::h2f90f14a08b46136
bitwarden_1  |   11:     0x55f4e2767707 - bitwarden_rs::mail::send_email::hc6a58f4d335b6f23
bitwarden_1  |   12:     0x55f4e275be9b - bitwarden_rs::api::identity::_password_login::hc94c89268309eb47
bitwarden_1  |   13:     0x55f4e276ff0b - bitwarden_rs::api::identity::rocket_route_fn_login::h2d556eb9b85d22b2
bitwarden_1  |   14:     0x55f4e2e0f4fe - <F as rocket::handler::Handler>::handle::h01f692faa3f33817
bitwarden_1  |   15:     0x55f4e2dfd5df - rocket::rocket::Rocket::route_and_process::h53823ecdf9d63d68
bitwarden_1  |   16:     0x55f4e2dfb7fe - <rocket::rocket::Rocket as hyper::server::Handler>::handle::h57dad1a8db723fc1
bitwarden_1  |   17:     0x55f4e2e19509 - hyper::server::Worker<H>::handle_connection::h8f3084327b42491d
bitwarden_1  |   18:     0x55f4e2e2557c - hyper::server::listener::spawn_with::{{closure}}::hf45b4cb01ebbac25
bitwarden_1  |   19:     0x55f4e2e209f7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h36cf34d028cd67d6
bitwarden_1  |   20:     0x55f4e2e1dc47 - std::panicking::try::do_call::h18eb8c48adc21269
bitwarden_1  |   21:     0x55f4e2f512ba - __rust_maybe_catch_panic
bitwarden_1  |                                at src/libpanic_unwind/lib.rs:82
bitwarden_1  |   22:     0x55f4e2dd9f0e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h401dd8d7bfeed135
bitwarden_1  |   23:     0x55f4e2f3714f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h352281c34878505f
bitwarden_1  |                                at /rustc/78ca1bda3522b14bc0336bc01dd1d49fdba2cda7/src/liballoc/boxed.rs:766
bitwarden_1  |   24:     0x55f4e2f50660 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h77507a97b5d0b6ca
bitwarden_1  |                                at /rustc/78ca1bda3522b14bc0336bc01dd1d49fdba2cda7/src/liballoc/boxed.rs:766
bitwarden_1  |   25:     0x55f4e2f50660 - std::sys_common::thread::start_thread::h8e874688d93a6d97
bitwarden_1  |                                at src/libstd/sys_common/thread.rs:13
bitwarden_1  |   26:     0x55f4e2f50660 - std::sys::unix::thread::Thread::new::thread_start::hbfd3b1248521427e
bitwarden_1  |                                at src/libstd/sys/unix/thread.rs:79
bitwarden_1  |   27:     0x7f38cd2374a4 - start_thread
bitwarden_1  |   28:     0x7f38ccd60d0f - __clone
bitwarden_1  |   29:                0x0 - <unknown>
```

The json error occurs in successful logons.

**Comment by dani-garcia** [comment]
This seems to happen because an error sending the login email, do you have it enabled and configured correctly?

**Comment by TuEstUnePommeDeTerre** [comment]
I have the SMTP settings set according to the wiki, but you're right; they do not seem to work.
The password hint page generates a similar error.

Interestingly though, the error persists with the SMTP configuration disabled.

Here is a redacted version of my docker-compose file:
```#docker-compose.yml

version: "3"

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    volumes:
      - ./bw-data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - private
    environment:
      WEBSOCKET_ENABLED: "true" # Required to use websockets
      SIGNUPS_ALLOWED: "false" # set to false to disable signups
      DOMAIN: "https://bitwarden.DOMAIN.com" # Enable U2F support
      SHOW_PASSWORD_HINT: "false" # Disable password hints on login page
      LOG_FILE: "/data/bitwarden.log" # Enable logging
      SMTP_HOST: "smtp.host.com"
      SMTP_FROM: "bitwarden@DOMAIN.com"
      SMTP_PORT: "587"
      SMTP_SSL: "true"
      SMTP_USERNAME: "USERNAME"
      SMTP_PASSWORD: "PASSWORD"
      DISABLE_ICON_DOWNLOAD: "true"
      DUO_IKEY: "IKEY"
      DUO_SKEY: "SKEY"
      DUO_HOST: "api-XXXXXXXX.duosecurity.com"
      RUST_BACKTRACE: "full"

  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - caddycerts:/root/.caddy
      - /etc/localtime:/etc/localtime:ro
    networks:
      private:
      docker_vlan:
        ipv4_address: 192.168.1.27
    environment:
      ACME_AGREE: "true" # agree to Let's Encrypt Subscriber Agreement
      DOMAIN: "bitwarden.DOMAIN.com" # Used for Auto Let's Encrypt SSL
      EMAIL: "email@DOMAIN.com" # Optional, provided to Let's Encrypt

volumes:
  caddycerts:

networks:
  private:
    internal: true
  docker_vlan:
    external:
      name: docker_vlan
```

**Comment by TuEstUnePommeDeTerre** [comment]
I gave up and just rebuilt the docker instance in a VM. I might have had a port closed somewhere. It's still weird to me that the email error was thrown even when the SMTP settings were not enabled.
