### ISSUE TITLE
Index column size too large

### ISSUE THREAD

**Issue by okami-chen** [dani-garcia/bitwarden_rs#986]
### Your environment

* Bitwarden_rs version: 

* Install method: 
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 

### Relevant logs

```php

Running migration 20180114171611
Executing migration script 20180114171611/up.sql
[2020-05-07 23:19:47][panic][ERROR] thread 'main' panicked at 'Can't run migrations: QueryError(DatabaseError(__Unknown, "Index column size too large. The maximum column size is 767 bytes."))': src/main.rs:336
   0: bitwarden_rs::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   2: rust_begin_unwind
             at src/libstd/panicking.rs:378
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at src/libcore/option.rs:1211
   5: bitwarden_rs::migrations::run_migrations
   6: bitwarden_rs::main
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:303
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  10: std::panicking::try
             at src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  11: main
  12: __libc_start_main
  13: <unknown>
```

**Comment by okami-chen** [comment]
where is `20180114171611/up.sql`

**Comment by dani-garcia** [comment]
You didn't specify database, so I'm gonna assume MySQL, because I've never heard about the error in SQLite, that file would be this one probably: https://github.com/dani-garcia/bitwarden_rs/blob/master/migrations/mysql/2018-01-14-171611_create_tables/up.sql

The error you get `The maximum column size is 767 bytes.` should probably require some changes to the database, which seems to have some maximum size for columns. Searching for that error gets some hits in Google with solutions, so I'd try those.

**Comment by BlackDex** [comment]
@okami-chen, did you got it working?

**Comment by okami-chen** [comment]
> @okami-chen, did you got it working?

yes

**Comment by BlackDex** [comment]
Great ☺️
